security:
    password_hashers:
        App\Entity\User:
            algorithm: auto

    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            lazy: true
            provider: app_user_provider
            form_login:
                login_path: login
                check_path: login
                username_parameter: email
                password_parameter: password
                default_target_path: /back-office
                enable_csrf: true
            logout:
                path: /logout
                target: /login

    access_control:
        - { path: ^/login, roles: PUBLIC_ACCESS }
        - { path: ^/signup, roles: PUBLIC_ACCESS }
        - { path: ^/forgot-password, roles: PUBLIC_ACCESS }  # Forgot password is accessible to everyone
        - { path: ^/send-otp, roles: PUBLIC_ACCESS }  # Send OTP is accessible to everyone
        - { path: ^/reset-password, roles: PUBLIC_ACCESS }  # reset password is accessible to everyone
        - { path: ^/verify-otp, roles: PUBLIC_ACCESS }  # Verify OTP is accessible to everyone
        - { path: ^/, roles: ROLE_USER }
