controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

cdn_cgi_rum:
    path: /cdn-cgi/rum
    controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController::urlRedirectAction
    defaults:
        path: /
